### ISSUE TITLE
Document UTF-8 only-ness in README

### ISSUE THREAD

**Issue by gsnedders** [google/gumbo-parser#10]
In the parser, there is a comment:

```
// NOTE(jdtang): Gumbo handles only UTF-8, so the encoding clause of the
    // spec doesn't apply.  If clients want to handle meta-tag re-encoding, they
    // should specifically look for that string in the document and re-encode it
    // before passing to Gumbo.
```

This UTF-8 only limitation should be documented. However, it is also true that to look for that string the client would need to implement a fair bit of the parser, to ensure they don't pick up something that looks like a meta element in a comment or attribute value or RAWTEXT element, etc. 

Ideally, surprisingly enough, support would be added for other encodings (if only optionally, though perhaps the default Windows-1252 should be built in), probably taking an encoding argument to the parser for when a higher level provides encoding metadata (be it HTTP's Content-Type or from a database of purely UTF-8 content), doing all the encoding detection and such like itself when not specified. Would there be any interest in adding such behaviour?

**Comment by nostrademons** [comment]
Done (at least the documentation).
