### ISSUE TITLE
Matching on local names instead of (ns, name) pair causes assertion from close_current_cell when dealing with math:td

### ISSUE THREAD

**Issue by gsnedders** [google/gumbo-parser#278]
More bugs from [afl](http://lcamtuf.coredump.cx/afl/)!

The following input:

    <table><th><math><td></tr>

Results in:

    get_title: src/parser.c:1497: close_current_cell: Assertion `!has_an_element_in_table_scope(parser, GUMBO_TAG_TH)' failed.

When processing the `</tr>` tag in the parser, the tree looks as follows:

```
html:html
  html:head
  html:body
    html:table
      html:tbody
        html:tr
          html:th
            math:math
              math:td
```

The `</tr>` starts off being processed "in foreign content" before falling back to the current HTML insertion mode ("in cell"). This then calls "close the cell" where Gumbo fails.

This appears to be the common HTML parser bug of matching on local name alone (it should be true that there is never both an `html:td` and an `html:th` in table scope at the asme time). I haven't looked at whether #274 fixes this, but it is certainly the case that html5lib-tests has tests for cases similar to this nowadays (though probably doesn't in the 0.95 version that Gumbo currently uses), so #3 is somewhat relevant here.

**Comment by gsnedders** [comment]
#279 turns out to be the same, except being during resetting the insertion mode instead of while popping elements from the stack.

**Comment by kevinhendricks** [comment]
If anyone is interested, please see the must recent pull request (number 5?) which I think is meant to address this very issue.
