### ISSUE TITLE
gumbo html parser bug

### ISSUE THREAD

**Issue by hotmocha** [google/gumbo-parser#292]
when parse a webhtml,  i find length will one more than the fact and the abnormal tag( t->v.element.tag ) is 826, so my code forced break. I think the gumbo parse the html error.
 for (i = 0; i < (&html->v.element.children)->length; i++) {
        GumboNode *t =   html->v.element.children.data[i];
        printf("%d\n", GUMBO_TAG_LAST);
        int d = t->v.element.tag;
        printf("%s\n", gumbo_normalized_tagname(d));
    }

**Comment by mYmNeo** [comment]
element child is not alway element, maybe text, so you should check child type to determine use which field in `v` union
