### ISSUE TITLE
gumbo.h includes tag_enum.h, which isn't installed via 'make install'

### ISSUE THREAD

**Issue by craigbarnes** [google/gumbo-parser#299]
The `gumbo.h` header now seems to [include](https://github.com/google/gumbo-parser/blob/517e04908442cf6cae4a2e50a73dcf18af56520e/src/gumbo.h#L161) a separate `tag_enum.h` header, as of commit 517e0490, but this header doesn't seem to get installed via `make install`. I haven't actually tested yet, but I'm guessing this will break compilation of any bindings that use installed (or packaged) headers.

**Comment by craigbarnes** [comment]
Just tested against libgumbo `master` to be sure. It errors out with:

```
fatal error: tag_enum.h: No such file or directory
```

**Comment by kevinhendricks** [comment]
Which branch is this for?  I thought the stable branch 0.9.4 did not use the tag.in approach with tag_enum.h.  But for v0.10.0 and v1.00 (equiv to master), that header would have to be installed properly.

**Comment by nostrademons** [comment]
He's working off master, which tracks the most recent (1.0.0).

I'll take a look.  I don't think there'll be any immediate breakage (wouldn't most people be installing the published releases, which don't have this problem?), but I'd like to keep head clean and usable via 'make install'.  (I wonder if I can get this test case into Travis so it'll notify me of any further install breakages.)

**Comment by craigbarnes** [comment]
>  I don't think there'll be any immediate breakage (wouldn't most people be installing the published releases, which don't have this problem?)

Yep, just to clarify, I didn't mean to imply this had broken bindings in any real scenario. I was just reading through the commit diff and noticed a new `#include` without a corresponding Makefile update. I'm still building/testing against the stable branch for now.

> I wonder if I can get this test case into Travis so it'll notify me of any further install breakages.

I have a test for lua-gumbo, that does a `make install DESTDIR=tmpdir` and then runs the test suite within that temporary installation. I guess gumbo could do something similar -- perhaps building one of the examples against the temporary installation.
