### ISSUE TITLE
Update to using latest html5lib-tests repo

### ISSUE THREAD

**Issue by gsnedders** [google/gumbo-parser#3]
There are various known bugs in what was current of 0.95 — if it is literally that, then by passing them you're violating the spec. It'd be nicer to use a git submodule for html5lib-tests, as then it's clear what revision of the testsuite you're currently using.

**Comment by nostrademons** [comment]
This has been done now for a while, using a git submodule to pull in the latest tests.  With 0.10.0, all of them pass except for one that I reported as a bug against the html5lib testsuite.

**Comment by paulirish** [comment]
Nice work!

**Comment by nostrademons** [comment]
Thanks!  @kevinhendricks and @vmg put in a bunch of work recently to get the template branch landed and a number of the smaller tests fixed.
