### ISSUE TITLE
API Documentation is missing or its location is not documented

### ISSUE THREAD

**Issue by michael-ts** [google/gumbo-parser#327]
The README.md5 file says "See the API documentation and sample programs for more details."  (no link provided) however I cannot find this referenced API documentation anywhere.  The sample programs in the "examples" directory do not contain said documentation.  The README gives a limited example of how to actual perform the parse, but tells me nothing about what the "GumboOutput" structure is or what can be done with it.  I have looked in all the sub-directories but see nothing documenting the API.

I found a separate page via Google (http://matze.github.io/clib-doc/gumbo-parser/index.html) but I don't know how it relates to this version, and it is very incomplete (for instance, I still don't see anything about the "GumboOutput" struct or what can be done with it.)

**Comment by craigbarnes** [comment]
The API docs can be generated by [doxygen](http://www.stack.nl/~dimitri/doxygen/):

    doxygen
    $BROWSER docs/html/index.html

**Comment by kiwidrew** [comment]
I would like to browse the API documentation, but don't particularly want to clone the repo and install `doxygen` yet.  Can you consider hosting the built docs somewhere?

**Comment by craigbarnes** [comment]
I think the project is more or less unmaintainted at this point, so I'd suggest just installing doxygen.

**Comment by duraki** [comment]
Can we not setup Github Pages with possible code / API usage?

**Comment by kevinhendricks** [comment]
FWIW, the complete user API is documented in gumbo.h.  If you are looking for examples for using the api, the serializer touches on most of the user side functionality of the library.  When accessed via python, the api is extended since  the C based parsed tree is converted to its bs4 equivalent after the parse completes.

**Comment by craigbarnes** [comment]
There's a copy of the Doxygen docs at https://craigbarnes.gitlab.io/lua-gumbo/libgumbo/gumbo_8h.html. It's for the fork of libgumbo used by lua-gumbo, but the API is still the same.
