### ISSUE TITLE
out of bounds read in  utf8_is_invalid_code_point

### ISSUE THREAD

**Issue by lcamtuf** [google/gumbo-parser#328]
Hey folks,

This causes a crash with prettyprint from Gumbo:

&#3000000000

It's because of this in utf8_is_invalid_code_point in src/utf8.c:

return (c < 0xFF && kInvalidSingleByte[c]) || ...

As it happens, c will be a negative integer, so you will get past the first check, and then reference kInvalidSingleByte[] out of bounds.

This probably has some security consequences for some uses of the library, as it may allow some information to be inferred about the contents of process memory that are unrelated to the parsed document.

**Comment by nostrademons** [comment]
Thanks for the report.  This is a regression introduced by #310, specifically [this commit](https://github.com/nostrademons/gumbo-parser/commit/e46e9e672497e42872d02497c8bda53f222a7067).  I can revert the commit - the speedup was quite marginal, and would probably disappear once the appropriate bounds checks are in.  It's not in any of the published releases (it's currently slated to go into 0.9.4 and 0.10.0, both of which haven't officially been cut yet), which should blunt the impact a bit, although @kevinhendricks, you should revert this commit in your Sigil branch.

Is there a good way to get a fuzzer into the unit tests?  I tend to depend upon the tests to catch regressions, and I'd love to be able to detect any future security problems before they get merged into head.

**Comment by lcamtuf** [comment]
I was running http://lcamtuf.coredump.cx/afl/ with a dictionary of tags extracted from tag_strings.h. It's not very unit-test-friendly because fuzzing is non-deterministic and can take a while, but maybe you wanna run a continuous session somewhere?

Also bumped into two other less interesting crashes so far, will file bugs.

**Comment by nostrademons** [comment]
Specific issue should be fixed via a revert in #332.  I looked into getting AFL running in a test (it doesn't specifically have to be a unit test, Travis just requires a command-line binary that can return with a zero or non-zero exit code), but I was worried that the amount of reps needed to test exhaustively would overload their servers.  Would be neat to have a continuous session going, but I don't personally have the budget or resources for it, so I think it has to wait until someone has server capacity to spare.

**Comment by kevinhendricks** [comment]
@nostrademus
Thanks for the head’s up!  Just reverted it.

>  although @kevinhendricks, you should revert this commit in your Sigil branch.
>
