### ISSUE TITLE
assert failure in handle_in_template

### ISSUE THREAD

**Issue by lcamtuf** [google/gumbo-parser#330]
printf '&lt;template&gt;\0' >foo.html

Causes assertion failure in:

prettyprint: src/parser.c:3596: _Bool handle_in_template(GumboParser *, GumboToken *): Assertion `0' failed.

Edit: fixed broken markup

**Comment by nostrademons** [comment]
Should be fixed with a test in #335.  Root cause was a missing check for GUMBO_TOKEN_NULL in the code.
