### ISSUE TITLE
Question about fragment parsing

### ISSUE THREAD

**Issue by karlwestin** [google/gumbo-parser#338]
Hi!
Not so much a bug as a question about fragment parsing and how its expected to work:
Im working on moving node-gumbo-parser over to 0.10.1 and am trying to figure out how i should present the fragment parsing:

```c++
    GumboOptions options = kGumboDefaultOptions;
    options.fragment_context = GUMBO_TAG_BODY;

    // here's my html
    char str[] = "<h1>Hi</h1>";

    GumboOutput* output = gumbo_parse_with_options(&options, str, 12);
    GumboVector children = output->root->v.element.children;
    printf("Elements length %d \n", (int)children.length);

    for(unsigned int i = 0; i < children.length; i++) {
      GumboNode* child = static_cast<GumboNode*> (children.data[i]);
      if(child->type == GUMBO_NODE_ELEMENT) {
        printf("Found element %s \n", gumbo_normalized_tagname(child->v.element.tag));
      } else if(child->type == GUMBO_NODE_TEXT) {
        printf("Found text %s \n", child->v.text.text);
      } else {
        printf("Got smth else \n");
      }
    }
```

When using the html `<h1>Hi<h1>`, i get exactly one child of output->root, which is the h1 tag, this is what i expect. But if i try to parse `<h1>Hi<h1><br>` i get 2 children, one h1 tag, and one **textNode** with the content "<". This is not what i expect. 

Is fragment parsing expected to take only one element? If so, what's expected to happen to the rest? Am i misunderstanding something?

Thanks,
Karl

**Comment by nostrademons** [comment]
I just tried writing a test case (#339) for this input and it passed.  Did you remember to update the hardcoded string length '12' when you changed the input?  That would give this results, as instead of pointing at the null terminator, str[12] points at the next '<' and then the input ends.

**Comment by karlwestin** [comment]
This is amazingly embarrassing! Thanks for pointing that out, now it works like i expected :)
