### ISSUE TITLE
bug in src/error.c when testing output of vnsprintf

### ISSUE THREAD

**Issue by kevinhendricks** [google/gumbo-parser#357]
In master in src/error.c at line 62, you check if the bytes_written > remaining_capacity but according to the man page of vnsprinf:

The vsnprintf() functions will write at most n-1 of the characters printed into the output string (the n'th character then gets the terminating `\0'); if the return value is greater than or equal to the n argument, the string was too short and some of the printed characters were discarded.  The output is always null-terminated.

The fix is simple change line 62 in src/error.c to:

```
if (bytes_written >= remaining_capacity) {
```

This will prevent a null from getting inserted into the error message being output anytime the bytes_written exactly equals the remaining capacity effectively truncating the error message.

**Comment by nostrademons** [comment]
My bad.  Will fix next time I'm looking at the code, or accept pull requests if someone gets to this before me.

**Comment by stevecheckoway** [comment]
Since this was fixed in https://github.com/google/gumbo-parser/commit/9faee7735a4c782c124d642df07b7789b6d3d8d7, should this issue be closed?
