### ISSUE TITLE
top level html tag generated during fragments parsing

### ISSUE THREAD

**Issue by ruz** [google/gumbo-parser#362]
Hi,

Implementing fragments parsing in perl bindings. Want to clarify if it's intentional that document and root of GumboOutput point at a html tag that was not in the input? Do I just skip it? Is it my fault and html tag shouldn't be there?

**Comment by nostrademons** [comment]
Yeah.  This is specified in the [HTML5 fragment parsing algorithm](https://html.spec.whatwg.org/multipage/syntax.html#parsing-html-fragments) - it's supposed to create Document and \<html> nodes automatically, and then begin parsing as if the context node were the last tag opened.  Note that this means that there will usually be a \<head> or \<body> node in the tree as well, depending on which section the fragment is legal in.

Depending on your use case, you may want to strip these out when returning the DOM fragment - some users will just want the fragment, others will want a complete legal HTML document.  We follow the spec and expect that client code will massage the tree in ways that are appropriate for them.

**Comment by ruz** [comment]
For test purposes I choose to use body tag as fragment_context and ```<div></div>``` as input. Parser returns ```<html><div></div></html>``` tree. So no body or head tags. My plan was to just skip root element, but from your words parser should generate more than just root html tag. Thoughts?

Going to read the algorithm.

**Comment by ruz** [comment]
Ok. I've read the algorithm. The last step says ```Return the child nodes of root, in tree order```, so fragment parser shouldn't return Document or html root tag (the only purpose of which is to setup context for the full parser algorithm). Let's consider that you wanted to preserve the old API (w/o fragments parsing) then you could return GUMBO_NODE_DOCUMENT with parsed element(s) in children vector and root pointer equal to NULL. What's done is done.

Also, looks like implemented parser doesn't allow user to set quirks mode (step #2 of the algo).
