### ISSUE TITLE
Getting the OuterHTML

### ISSUE THREAD

**Issue by RachidTagzen** [google/gumbo-parser#374]
Hi,

How can I get the OuterHTML (not just the InnerText) of a specific Tag.
For example, If I want to get the **div** tag with **class="content"** from this HTML source:

```
<html>

   <head>
      <title>My Title</title>
      <meta content="">
      <style></style>
   </head>
   
   <body>
      <h3>First header</h3>
      <p>text text text</p>
      <div class="content">
         <h3>My Text 0<a href="https://www.google.com">The site of google</a></h3>
      </div>
      <div>
         My Text 1
         <div class="cls">My Text 2
         <h1>My Text 3</h1>
      </div>
      </div>
   </body>
   
</html>
```

**The result I want extract:**

```
<div class="content">
    <h3>My Text 0<a href="https://www.google.com">The site of google</a></h3>
</div>
```

Thanks.

**Comment by craigbarnes** [comment]
The `Element.outerHTML()` method from the DOM spec serializes the DOM tree to a string of HTML. My [lua-gumbo] library uses a DOM tree that supports the `outerHTML` method. Even if you don't want to use Lua, the [code] may be useful for reference.

[lua-gumbo]: https://github.com/craigbarnes/lua-gumbo
[code]: https://github.com/craigbarnes/lua-gumbo/blob/8d3b006a044106a0006f77791f292585bf5288f4/gumbo/dom/Element.lua#L216-L263
