### ISSUE TITLE
Parsing unicode characters in attribute

### ISSUE THREAD

**Issue by Hartigan** [google/gumbo-parser#379]
I have simple html page http://pastebin.com/YeaGNJLb
Assert was triggered in function `isalnum`(gumbo-parser/src/char_ref.rl) when html attribute has specific unicode symbols.

**Comment by kevinhendricks** [comment]
FWIW, I am not seeing that at all with Sigil's fork of gumbo.  Gumbo only accepts utf-8 encoded files.  It assumes all other encodings have been converted to utf-8 before being passed to the parser.  Are you sure your test file has been properly encoded as utf-8?

Here is the only "error" associated with your file when passed through our gumbo "well_formed" check:

```
kbhend$ ./well_formed ~/Desktop/html_unicode_attribute.html
<!DOCTYPE html>
<html>
<head>
    <title>
        Test page for gumbo parser
    </title>
</head>
<body>
    <div>
        <img src="http://localhost?value=0&ampÍ¾label=0" />
    </div>
</body>
</html>
--------
line: 10 col: 43 type 6 @10:43: The named character reference &amp should be followed by a semicolon.
@10:43: The named character reference &amp should be followed by a semicolon.
        <img src="http://localhost?value=0&ampÍ¾label=0" />
                                          ^
```

**Comment by Hartigan** [comment]
Thanks.

**Comment by Hartigan** [comment]
I tested that page for linux and windows debug builds:
- linux gcc: no asserstion in 'isalnum' function
- windows msvc14: assert was triggered if symbol is not in range [-1; 255]

**Comment by kevinhendricks** [comment]
You might want to take a peek at this:

https://social.msdn.microsoft.com/Forums/vstudio/en-US/464a8b9f-a999-4b63-a3b0-79b9c2ef3df8/bug-isalnum-asserts-in-debug-build?forum=

It seems that msvc has a strange way of implementing isalnum especially if the char type in the compiler defaults to a signed type.  You would need to check first for the EOF value (typically -1) and then convert any other signed value (negative if byte value is greater than 127) into the unsigned range (0 to 255) and pass its value to isalnum as a signed int to get things to work right on Windows using msvc.

You might want to add a macro or wrapper function to handle this as a straight cast to unsigned char first would lose EOF compliance.

Neither linux or osx (bsd) has this issue with their implementation of isalnum.

That said, if using utf-8, you should not need or use a locale dependent function like isalnum().
