### ISSUE TITLE
soup adapter differs to BS4 in behaviour regarding whitespace in attributes

### ISSUE THREAD

**Issue by rofl0r** [google/gumbo-parser#385]
note: i use bs4 support from #368 if that is relevant

i have an issue with code of the form
```html
<div class="foo bar">baz</div>
```
with the real bs4, it's possible to find above snippet via 
```py
div = soup.body.find('div', attrs={'class':'foo'})
```
that means it matches any of the whitespace-separated attributes.
but with gumbo's soup adapter i need to use the full attribute string:
```py
div = soup.body.find('div', attrs={'class':'foo bar'})
```

additionally, if the div is already selected, beautifulsoup itself makes the attrs available as list, while gumbo as string.
in bs4:
```py
if div.attrs['class'][0] == 'foo': found()
```
with gumbo:
```py
if div.attrs['class'] == 'foo bar': found()
```
this is annoying when porting already working code using bs4 to use gumbo.

**Comment by kevinhendricks** [comment]
You might want to check out our modified version here:

https://github.com/Sigil-Ebook/Sigil/blob/master/src/Resource_Files/plugin_launchers/python/sigil_gumbo_bs4_adapter.py

Especially this routine:
```
def _convert_attrs(element_attrs):
    def maybe_namespace(attr):
        if attr.namespace != gumboc.AttributeNamespace.NONE:
            name = _fromutf8(attr.name)
            prefix = repr(attr.namespace).lower() if name != 'xmlns' else None
            nsurl = attr.namespace.to_url()
            return sigil_bs4.element.NamespacedAttribute(prefix, name, nsurl)
        else:
            return _fromutf8(attr.name)
    def maybe_value_list(attr):
        value = _fromutf8(attr.value)
        if " " in value:
            if _fromutf8(attr.name) == "class" and attr.namespace == gumboc.AttributeNamespace.NONE:
                value = sigil_bs4.element.whitespace_re.split(value)
        return value
    return dict((maybe_namespace(attr), maybe_value_list(attr)) for attr in element_attrs)

```

**Comment by kevinhendricks** [comment]
For more info see:  
https://github.com/google/gumbo-parser/issues/345

Specifically the patch here offered over 2 years ago:

https://gist.github.com/kevinhendricks/2025df8d7161168d7ecc

**Comment by rofl0r** [comment]
thanks for your reply.
is your patch from #345 equivalent to what you have in that sigil repo, or is the latter more advanced?
(btw, i tried gumbo because i hoped to get better performance with BS4, but the time spent in the gumbo bs4 adapter, especially add_element, is as bad or even worse than bs4 with html.parser...)

**Comment by kevinhendricks** [comment]
#345 was built for google's gumbo, whereas the Sigil repo link is for a Sigil specific forks of gumbo and bs4.  They are very close but not exact.  Stick with the #345 patch to get something working for general bs4 and gumbo.

Yes, parsing something first with gumbo and then walking the entire gumbo node tree simply to effectively clone it to create a bs4 tree will never be hugely fast.  Inside our own fork, we have added simple editing capabilities to gumbo and a C++ class around it to work directly with the gumbo tree to get the performance we need taking advantage that the gumbo code base is re-entrant.  We use our fork of bs4 with our fork of gumbo only in our plugin python3 framework.

**Comment by rofl0r** [comment]
now you made me curious :)
would you mind supplying a link to the C++ class and some code using it ?
i tried already a lot of different things, but couldnt yet get a satisfying performance out of bs4.... so i doubt that patching vanilla gumbo with your gist will make any difference.

**Comment by kevinhendricks** [comment]
Our forked version of gumbo (with additions for simple editing of nodes and to support xhtml syntax as well as html syntax) can be found here:

    https://github.com/Sigil-Ebook/Sigil/tree/master/internal/gumbo

Our C++ class we wrapper gumbo with can be found here:

    https://github.com/Sigil-Ebook/Sigil/blob/master/src/Misc/GumboInterface.h
    https://github.com/Sigil-Ebook/Sigil/blob/master/src/Misc/GumboInterface.cpp

We use this class with QtConcurrent to simultaneously parse every xhtml file in parallel inside an ebook when opening it.
It is a bit specific to Sigil but things like serialization, pretty-printing of nodes back to strings, and easily extractable away from Qt classes if needed.

Feel free to tear it apart and reuse any of it as I was the original author and can give you whatever rights you need to for your project’s license.  Same goes for our gumbo changes.

**Comment by kevinhendricks** [comment]
Oh and examples of using it can be found in many places in Sigil’s github tree by simply searching the repository for GumboInterface

**Comment by rofl0r** [comment]
just that i understand you correctly - the C++ wrapper is not used to speed up python code, right ?

**Comment by kevinhendricks** [comment]
Correct.  If you want fast python code use the python  ctypes interface to gumbo directly  (not with bs4 in between) and write your own interface routine implementing whatever searches you want in multiprocess if need be  to spead up large amounts of parsing done in parallel.
