### ISSUE TITLE
Public error reporting API

### ISSUE THREAD

**Issue by craigbarnes** [google/gumbo-parser#39]
Is there anything a contributor could do to help make the error reporting API public? Any tips on issues I might come accross if I just go ahead and try? I'd like to use Gumbo as the basis for a lint tool, so it seems helping with this would be a good start.

**Comment by kevinhendricks** [comment]
A public interface for errors is still really needed.  To do basic sanity checks on epub xhtml pages before loading then in a QWebView widget, I woud love to get back a basic "its okay" check that lays out nicely where the error is (line number and column) and a basic error message.

Right now to do that I have to include error.h and do something like the following just to get the errors in my own well_formed.cc example:

[CODE]
  ...
  GumboOutput* output = gumbo_parse_with_options(&myoptions, contents.data(), contents.length());
  GumboParser parser;
  parser._options = &myoptions; 
  const GumboVector* errors  = &output->errors;
  for (int i=0; i< errors->length; ++i) {
    GumboError* er = static_cast<GumboError*>(errors->data[i]);
    unsigned int linenum = er->position.line;
    unsigned int colnum = er->position.column;
    unsigned int typenum = er->type;
    GumboStringBuffer text;
    gumbo_string_buffer_init(&parser, &text);
    gumbo_error_to_string(&parser, er, &text);
    std::string errmsg(text.data, text.length);
    fprintf(stdout, "line: %d col: %d type %d %s\n", linenum, colnum, typenum, errmsg.c_str());
    gumbo_string_buffer_destroy(&parser, &text);
    // gumbo_print_caret_diagnostic(&parser, er, contents.c_str());
  }
  gumbo_destroy_output(&myoptions, output);
[/CODE]

I used to stop at the first error by setting that in options, but there is a bug someplace in the code that sets has_error to true when there is no actual errors stored by the parser.  Making stopping, less than worthwhile.

I was thinking that has_error at the end of parser.c might want to simply check to see if the length of the error vector is > 0 before actually stopping on the first error.

So I was wondering what your plans and timeline are for making an error interface available?

Thanks,

Kevin

**Comment by nostrademons** [comment]
What is it that you'd like to see, ideally, for an API?  The biggest blocker is that we don't really know what such an API should look like.  So if you could give us an idea of what the use-case is, what sort of errors would be most helpful, and how you plan to display or otherwise handle them, that'd be helpful.

error.h is currently considered internal/unstable - it provides a low-level API that does what the spec says, but isn't all that useful for client code.  It's probably possible to recover most of the useful error information from it, but not easy.

**Comment by stevecheckoway** [comment]
I found the api in error.h to be [almost exactly](https://github.com/rubys/nokogumbo/pull/46/commits/e361b49eff45c0ac72837b53a3b1850db45764ab) what I wanted for Nokogumbo. The one thing that seemed awkward was constructing the fake `GumboParser` to pass the options in.
