### ISSUE TITLE
question: walking the tree

### ISSUE THREAD

**Issue by magna25** [google/gumbo-parser#394]
This might be a silly question but can't find the examples on how to walk the output tree.

```
GumboOutput* output = gumbo_parse("<h1>Hello  <span>World!</span></h1>");

GumboNode* root = output->root;
```

```
<body>
	<div>
		Hello <span>World!</span>
		<div>
			<span>I'm a span</span>
		</div>
	</div>
	<div id="test">Second div</div>
</body>
//trying to turn the above html in to something like below

Node[0] => {
	tagName: "body",
	text: null,
	Attributes: null,
	children: {
		Node[0] => {
			tagName: "div",
			text: "Hello",
			Attributes: null,
			children: {
				Node[0] => {
					tagName: "span",
					text: "World!",
					Attributes: null,
					children: null
				}
				Node[1] => {
					tagName: "div",
					text: null,
					Attributes: null,
					children:{
						Node[0] => {
							tagName: "span",
							text: "I'm a span",
							Attributes: null,
							children: null
						}
					}
				}
			}
		}
		Node[1] => {
			tagName: "div",
			text: "Second div",
			Attributes: {"id": "test"},
			children: null
		}
	}
	
}


```

**Comment by kevinhendricks** [comment]
See examples/serialize.cc that uses recursion to walk and rebuild the tree here:
https://github.com/google/gumbo-parser/blob/master/examples/serialize.cc

Also see https://github.com/google/gumbo-parser/pull/392/commits/7f73b3b836ae75bb40c3ce1bff46c1ac913a2cae

A pull request that includes a non-recursive tree traversal routine.

**Comment by magna25** [comment]
Thanks

**Comment by magna25** [comment]
@kevinhendricks found the recursive function very useful but was wondering if there was anyway to determine the relationship (parent and child) between the nodes. Is there like `has_children()` method or something?

**Comment by kevinhendricks** [comment]
In the recursion routine serialize_contents processes each child of the parent it is called from in serialize.   Please example gumbo.h for info on the node structure, how children are stored, and how pointer back to parent is stored.

**Comment by data-man** [comment]
Try [MyHTML](https://github.com/lexborisov/myhtml) or [Modest](https://github.com/lexborisov/Modest) and be happy.
