### ISSUE TITLE
Wrong parsing of web components (ie polymer) tags

### ISSUE THREAD

**Issue by essenciary** [google/gumbo-parser#402]
I'm using gumbo-parser from Julia and when attempting to parse web components tags, this happens: 

```julia
julia> Gumbo.parsehtml("""<px-spinner size="100"></px-spinner>""")
julia> HTML Document:
<!DOCTYPE >
<HTML>
  <head></head>
  <body>
    <px-spinner size="100" size="100"></px-spinner size="100">
  </body>
</HTML>
```

**Comment by essenciary** [comment]
I understand the issue might be caused by the Julia wrapper. The maintainer can't check so I'll take a look -- I'll report back my findings.

**Comment by craigbarnes** [comment]
It's almost certainly the Julia wrapper. Using the lua-gumbo tree builder and serializer, I get:

```
<html>
    <head></head>
    <body>
        <px-spinner size="100"></px-spinner>
    </body>
</html>
```

**Comment by essenciary** [comment]
Thanks, indeed :) 
This should be closed though -- I've made a PR with the fixes months ago and was already merged.
