### ISSUE TITLE
 <!doctype html> is missing

### ISSUE THREAD

**Issue by idofilus** [google/gumbo-parser#405]
Seems like someone already opened an issue about this: https://github.com/google/gumbo-parser/issues/65
Anyone managed to get the output contain the doctype data ? 
There is no a single `node->type == GUMBO_NODE_DOCUMENT`.

**Comment by kevinhendricks** [comment]
Check out the examples/serialize.cc to see how to work with the doctype document node.  Add nodes of a document are children if this node.   Use output->document to get this node not output->root as that points to the html node not the document node

**Comment by idofilus** [comment]
Thanks :)
