### ISSUE TITLE
MSVC: <strings.h> does not exist in Windows

### ISSUE THREAD

**Issue by kolomenkin** [google/gumbo-parser#411]
There is no `<strings.h>` in Windows.

Only two functions are needed by gumbo parser from `<strings.h>`:
- `strcasecmp`
- `strncasecmp`

`_stricmp` from `<string.h>` completely does the same as `strcasecmp`
`_strnicmp` from `<string.h>` completely does the same as `strncasecmp`

Here is my solution for Windows:

```
#if defined(_WIN32) || defined(_WIN64) 
#  include <string.h>
#  define strcasecmp _stricmp 
#  define strncasecmp _strnicmp 
#else
#  include <strings.h>
#endif
```

**Comment by crazydef** [comment]
This solution doesn't work because compilers on Linux don't handle directory paths the same way as Visual Studio does.  They always start with the current directory, and so the #include <strings.h> results in a circular include that never exits.

**Comment by craigbarnes** [comment]
It's not really correct to use `strcasecmp()` anyway, since it's locale-dependant. The various forks of Gumbo did away with the portability issue and the locale issue by just using a custom, [ASCII-only equivalent](https://github.com/craigbarnes/lua-gumbo/blob/master/lib/ascii.h#L35-L47), as dictated by the spec.

**Comment by kolomenkin** [comment]
You are talking `#include <strings.h>` will not work in Linux. But this is the original code. It is used in gumbo parser for years.

My proposal was to add some `ifdef` and have workaround for Windows too.

**Comment by kolomenkin** [comment]
We could have file like `local_strings.h` with the code from my proposal.
And update Gumbo parser to include `"local_strings.h"` instead of `<strings.h>`
