### ISSUE TITLE
Proposal for public tokenizer API

### ISSUE THREAD

**Issue by mato** [google/gumbo-parser#64]
I have a use case where I only need to tokenize a HTML document up to a certain point, not build a full parse tree. For this I'd like to propose the addition of a public tokenizer API to Gumbo.

Here is a first cut of what such an API could look like:

```
typedef struct {
    /* encapsulates a struct GumboInternalParser */
    void* _parser;
} GumboTokenizer;

GumboTokenizer* gumbo_tokenizer_init(
    const char *buffer, size_t buffer_length);
/* a _with_options variant can be provided here */

bool gumbo_tokenizer_lex(
    GumboTokenizer* tokenizer, GumboToken* output);

void gumbo_tokenizer_destroy(GumboTokenizer* tokenizer);

void gumbo_tokenizer_token_destroy(
    GumboTokenizer* tokenizer, GumboToken* token);
```

Example usage:

```
GumboTokenizer *tokenizer = gumbo_tokenizer_init(text, text_size);
while (1) {
  GumboToken token;
  gumbo_tokenizer_lex(tokenizer, &token);
  if (token.type == GUMBO_TOKEN_EOF)
    break;
  /* do stuff with token */
  gumbo_tokenizer_token_destroy(tokenizer, &token);
}
gumbo_tokenizer_destroy(tokenizer);
```

The API would also require making the `GumboTokenType`, `GumboTokenDocType`, `GumboTokenStartTag` and `GumboToken` types public.

I'm not entirely happy with having to drag `GumboTokenizer` around but the only alternative would seem to be a callback-based API which is a pain to use. 

What do you think? I'm happy to submit a pull request after I get some review from other users.

**Comment by RReverser** [comment]
This seems to be working now (at least I was able to use that API directly).
